package com.cauldron.myriad.engine

import com.cauldron.myriad.engine.model.Action
import com.cauldron.myriad.engine.model.Mode
import com.cauldron.myriad.engine.model.MoveId
import com.cauldron.myriad.engine.persist.SaveCodec
import com.cauldron.myriad.engine.persist.SaveFile
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertIs
import kotlin.test.assertTrue

/**
 * The golden-save corpus (MASTER_PLAN §8): byte-frozen saves from every released
 * format version must load forever. v1 fixtures were generated by the actual v1
 * engine before the M1a changes landed.
 */
class MigrationTest {

    private fun golden(name: String): ByteArray =
        checkNotNull(javaClass.getResourceAsStream("/golden/$name")) { "missing fixture $name" }.readBytes()

    private val engine = Engine(TestWorlds.cellarLike())

    @Test
    fun `v1 exploring save loads, migrates, and plays on`() {
        val save = SaveCodec.decode(golden("v1-exploring.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, save.formatVersion, "decode must migrate to current")
        assertIs<Mode.Exploring>(save.state.mode)
        assertTrue(TestWorlds.SWORD in save.state.player.inventory, "fixture had taken the sword")

        // It must be playable, not just loadable: equip, fight smart, climb out.
        var state = engine.step(save.state, Action.Equip(TestWorlds.SWORD)).state
        state = engine.step(state, Action.Move(TestWorlds.PASSAGE)).state
        state = fightSmart(engine, state)
        if (state.mode is Mode.Exploring) {
            state = engine.step(state, Action.Move(TestWorlds.STAIR)).state
            assertIs<Mode.Victory>(state.mode)
        } else {
            assertIs<Mode.Dead>(state.mode) // honest outcome; never a crash
        }
    }

    @Test
    fun `v1 mid-combat save resumes ready to act with sentinel intent`() {
        val save = SaveCodec.decode(golden("v1-combat.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, save.formatVersion)
        val mode = assertIs<Mode.Combat>(save.state.mode)

        // Migration defaults: player ready, monster winding up, full stamina, sentinel intent.
        assertEquals(Mode.Combat.GAUGE_MAX, mode.playerGauge)
        assertEquals(0, mode.monsterGauge)
        assertEquals(Mode.Combat.STAMINA_MAX, mode.playerStamina)
        assertEquals(false, mode.braced)
        assertEquals(MoveId(""), mode.monsterIntent)

        // The sentinel must resolve and the fight must complete without crashing.
        val finished = fightSmart(engine, save.state)
        assertTrue(
            finished.mode is Mode.Exploring || finished.mode is Mode.Dead,
            "migrated combat must finish cleanly, ended in ${finished.mode}"
        )
    }

    @Test
    fun `v2 exploring fixture chains to current and plays on`() {
        val save = SaveCodec.decode(golden("v2-exploring.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, save.formatVersion, "v2 must chain 2→3")
        assertIs<Mode.Exploring>(save.state.mode)
        assertEquals(TestWorlds.SWORD, save.state.player.equipped, "fixture was armed")
        assertTrue(save.state.meters.isEmpty(), "meters arrive empty; meterFor seeds reads")
        engine.step(save.state, com.cauldron.myriad.engine.model.Action.Look)
    }

    @Test
    fun `v2 mid-combat fixture resumes with its real telegraph and brace intact`() {
        val save = SaveCodec.decode(golden("v2-combat.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, save.formatVersion)
        val mode = assertIs<Mode.Combat>(save.state.mode)
        assertTrue(mode.monsterIntent.value.isNotEmpty(), "v2 saves carry a real drawn intent, not the sentinel")
        assertTrue(mode.braced, "the fixture braced and the rat hadn't struck yet")
        assertEquals(Mode.Combat.GAUGE_MAX, mode.playerGauge)
        assertTrue(mode.monsterGauge in 1 until Mode.Combat.GAUGE_MAX, "monster gauge mid-charge")

        val finished = fightSmart(engine, save.state)
        assertTrue(finished.mode is Mode.Exploring || finished.mode is Mode.Dead)
    }

    @Test
    fun `v3 fixtures chain to current with level-1 progression defaults`() {
        // frostbitten world matches the fixture's generator (has the warmth meter).
        val frostEngine = Engine(TestWorlds.frostbitten(cap = 6))
        val exploring = SaveCodec.decode(golden("v3-exploring.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, exploring.formatVersion, "v3 must chain 3→4")
        assertIs<Mode.Exploring>(exploring.state.mode)
        // Progression fields arrive at their defaults.
        assertEquals(1, exploring.state.player.level)
        assertEquals(0L, exploring.state.player.xp)
        assertEquals(0, exploring.state.player.skillPoints)
        assertTrue(exploring.state.player.unlockedNodes.isEmpty())
        assertTrue(exploring.state.player.mastery.isEmpty())
        frostEngine.step(exploring.state, Action.Look) // must play on

        val combat = SaveCodec.decode(golden("v3-combat.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, combat.formatVersion)
        val mode = assertIs<Mode.Combat>(combat.state.mode)
        assertTrue(mode.abilityCooldowns.isEmpty(), "migrated combat has no cooldowns")
        val finished = fightSmart(frostEngine, combat.state)
        assertTrue(finished.mode is Mode.Exploring || finished.mode is Mode.Dead)
    }

    @Test
    fun `v4 fixtures chain to current and play on`() {
        val exploring = SaveCodec.decode(golden("v4-exploring.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, exploring.formatVersion, "v4 must chain 4->5")
        assertIs<Mode.Exploring>(exploring.state.mode)
        engine.step(exploring.state, Action.Look)

        val combat = SaveCodec.decode(golden("v4-combat.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, combat.formatVersion)
        val mode = assertIs<Mode.Combat>(combat.state.mode)
        assertTrue(mode.statuses.isEmpty(), "migrated combat has no active statuses")
        val finished = fightSmart(engine, combat.state)
        assertTrue(finished.mode is Mode.Exploring || finished.mode is Mode.Dead)
    }

    @Test
    fun `v5 fixtures chain to current and play on`() {
        val exploring = SaveCodec.decode(golden("v5-exploring.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, exploring.formatVersion, "v5 must chain 5->6")
        assertIs<Mode.Exploring>(exploring.state.mode)
        assertTrue(exploring.state.flags.isEmpty(), "migrated save has no story flags")
        engine.step(exploring.state, Action.Look)

        val combat = SaveCodec.decode(golden("v5-combat.myr"))
        assertEquals(SaveCodec.FORMAT_VERSION, combat.formatVersion)
        assertIs<Mode.Combat>(combat.state.mode)
        val finished = fightSmart(engine, combat.state)
        assertTrue(finished.mode is Mode.Exploring || finished.mode is Mode.Dead)
    }

    @Test
    fun `v2 saves pass through migration unchanged`() {
        val state = engine.newGame(11, "Hero")
        val save = SaveCodec.fresh(state)
        assertEquals(save, SaveCodec.decode(SaveCodec.encode(save)))
    }

    @Test
    fun `unknown old versions are refused loudly`() {
        val bogus = SaveFile(formatVersion = 0, engineVersion = "0.0.1", state = engine.newGame(1, "X"))
        assertFailsWith<SaveCodec.CorruptSaveException> { SaveCodec.decode(SaveCodec.encode(bogus)) }
    }
}
